name: Contact Us
description: Get in touch with the Tree of Sex Ontology team.
title: '[Contact Us]: '
labels: ['connect']
assignees:
  - ccaio
body:
  - type: markdown
    attributes:
      value: |
        Thanks for getting in touch with us.
  - type: dropdown
    id: team
    attributes:
      label: Which Tree of Sex operation team do you want to connect with?
      options:
        - ontology
        - database integration
        - ethics and inclusion
        - literature search
        - other
    validations:
      required: true
  - type: textarea
    id: message
    attributes:
      label: Message
      description: If you have a problem or feature request for a TOSO term, please create an issue on the respective GitHub page directly.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://docs.google.com/document/d/1Mzyio-2NLZyrNH9J5pwOKtM2FuDFPL_QNGU31NrbZfQ/edit#heading=h.j2ubdz5q2r0u)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
